### ISSUE TITLE
Custom import hooks

### ISSUE THREAD

**Issue by bassplayer7** [SnowdogApps/magento2-theme-blank-sass#117]
I'm building a custom theme as a child of this blank SASS theme. I looked for a SASS import in `styles.css` that I could override to include other partials but wasn't seeing anything that looked like it was set up for that. I was wondering about adding some files that would essentially be hooks for a child theme to be able to either override previously set variables, or include other partials all together. Right now, any SASS file can easily be overridden by following the Magento approach of including a file with the same name and path in the child theme. My idea is to add at least two `@import`'s to `styles.scss`. The files would need to be included in the base theme as well but could be empty or include an explanatory comment.

The first file would be immediately after line 9: `@import 'variables';`. It would be something like: 

```css
@import 'theme/variables';
```

The second file would be somewhere near the end:

```css
@import 'theme/styles';
```

This way, I could add a `theme` folder in my theme with the partials and then override variables and add other partials.

Would this be of benefit or would it be out of character with Magento?

**Comment by Igloczek** [comment]
You should overwrite partials directly, not via adding yet another messy folder with you custom styles to override default styles just using higher specificity. It's not Magento way, nor a good practise of writing styles.

Closing due to lack of "issue" part in this "issue".
If you want to just talk about project, use Magento Community forum - link is in readme.

**Comment by bassplayer7** [comment]
@Igloczek perhaps I wasn't clear. The purpose would not be to override existing styles, which would indeed require a higher specificity (very bad!). While some developers could still misuse it to do that, the use would be for non-native UI elements which I think nearly every custom theme would have. Something such as a banner with a link over it that is managed from the CMS. (And apart from styles for a module's HTML).

As it is, the current styles are (in my opinion) nothing short of a disaster with specificity through the roof on many, or most elements. As a result, the less partials that I need to override in order to **add** styles the better.

Also, consider that this is actually what Magento does as well. [In this topic](http://devdocs.magento.com/guides/v2.0/frontend-dev-guide/css-guide/css_quick_guide_approach.html), they describe an approach to **add**  styles. It seems that overriding the entire `styles.scss` to **add** styles decreases the ease of upgrading in the future.

Does this make more sense?

**Comment by Igloczek** [comment]
If you need to add custom features, just add them, but I'll suggest to keep "Magento-like" folder structure, not just `/theme` in root, but at all it's up to you, it will works anyway.

For me solving issues in `styles.scss` is probably the easies things to do when it comes to any kind of conflicts. This file contains only imports, so it's super easy to add another or remove something in any time.

BTW. I understand that Magento (front-end) rules shouldn't be always taken as good pattern like 2 years ago and I ready suggest to follow this approach of "parsing" their docs and other "how to's" 😉

**Comment by bassplayer7** [comment]
@Igloczek thanks for the reply and clarification. I suppose it still seems to me that if overriding a large file is not necessary, then it is not a superior approach. 

I was having a little trouble understanding your last paragraph. Are you saying that the topic I linked to isn't best practice (would this be per Magento or the front end community?) and as such, a file that is similar in concept to `_extend.less` is not good?

Since I digress on the previous paragraph, I would happy to open a form topic if you prefer. Thanks.

**Comment by Igloczek** [comment]
I believe is single purpose rule and high modularity. This is in my opinion a good practice worth follow in every project, not only this one related to Magento.

Creating files like `_extend.less` is agains this rules, b/c lead to have super long files (i.e. 2-3k LoC) without any strict purpose, it's just a box for everything, I'd even say it's a "box of shame" 😉
It's hard hard to read, overwrite, update, remove, refactor etc. this type of code.

And that's why I'm not following blindly Magento's "good practices", b/c they are not always good, especially this one related to front-end. If they will know how to build a good fornt-end rules and follow them, this project will never exist 😉
