### ISSUE TITLE
Suggestion: remove nesting and extends

### ISSUE THREAD

**Issue by microcipcip** [SnowdogApps/magento2-theme-blank-sass#128]
Is there any chance of being able to remove the nesting and recommand something like BEM for future development? Same for extends, I'd use mixins instead as many have pointed out in the SASS community that extends are evil.

This will make frontend developers life easier as we won't have problems overriding something like this:
```
.navigation .level0 > .level-top:hover, .navigation .level0 > .level-top.ui-state-focus {  }
```
As it could potentially (with BEM) become something more managable, like this:
```
.nav-level0__link {  }
```

**Comment by Igloczek** [comment]
You know it's tens thousands of selectors (there is about 1000 templates across all modules, for a "Blank" theme) to "translate" and everything will blow up due to lack of backward compatibility? (excluding thousands of work hours from "issue" scope)

BEM is our long term goal, but it's still under consideration and heavy discussion with Magento core team. If you want more please follow talks on [Magento Community Forum](https://community.magento.com/t5/Less-to-Sass-Community-Project/bd-p/less-to-sass) and [my twitter account](https://twitter.com/Igloczek).

Closing, b/c it's not an issue report.

**Comment by microcipcip** [comment]
Thanks for the reply, I'll wait for Magento 3.0
