### ISSUE TITLE
Missing theme after magento upgrade 2.1.9

### ISSUE THREAD

**Issue by RafaelAgeno** [SnowdogApps/magento2-theme-blank-sass#157]
After upgrading magento from 2.1.7 to 2.1.9 magento returns error theme_dir is missing. On setup:static-content:deploy theme Snowdog/blank is missing and during setup:upgrade theme is not added to theme table.

Is theme compatible with w magento 2.1.9 ?

**Comment by Igloczek** [comment]
It should, I'm not aware of any changes in the area of registering themes in 2.1.9, nor 2.1.8.

Remember that in production mode you can't register a new theme.

**Comment by mattkrupnik** [comment]
Hi,
I have this same problem with 2.2 version? Any ideas?

**Edit**
Theme is set as parent for my child theme, magento2-theme-blank-sass was placed in vendor directory, since Magento 2.2 upgrade magento2-theme-blank-sass theme is missing like @RafaelAgeno wrote. Today I moved magento2-theme-blank-sass to app directory where is placed my main theme and it works, but think that should't be like that.

Regards
Matt

**Comment by Igloczek** [comment]
I just tested both 2.1.9 and 2.2.0, in both cases in `developer` mode during `setup:upgrade`theme was registered correctly.

You are probably doing something wrong or this is a core issue, that should be reported [here](https://github.com/magento/magento2/issues)
