### ISSUE TITLE
Blank Theme flexibility

### ISSUE THREAD

**Issue by Ig0r-M-magic42** [SnowdogApps/magento2-theme-blank-sass#192]
**Given** current theme uses .scss
**Whereas** Magento 2 default theme comes in .less (hopefully will be changed in future)
**And** magento 2 third party extensions use .less files
**Then** there is required a flexibility so that
**After** moving .less to .scss they need to be included in snowdog theme or custom one.

### Proposed solution
Update `vendor/snowdog/theme-blank-sass/styles/styles.scss` file to include following:
@import 'blocks/third-party';
@import 'blocks/components/third-party';
@import 'blocks/third-party';
@import 'blocks/widgets/third-party';

This will allow developer who are using your theme after transforming .less files of a third party extension to .scss to include it properly in the snowdog blank theme, if above files are places near their type then it will be available variables and mixins for new files.

## Currently
Developer is required to copy whole `styles.scss` and add his configuration.

**Comment by Ig0r-M-magic42** [comment]
Proposed files should be empty so we could just create them in our theme, and in `var/view_processed` they will be merged.

**Comment by Igloczek** [comment]
The Blank theme is not meant to be used directly, but as a parent of own custom theme, so if you need such imports, add them to your project.

Adding empty files and new imports just because someone might want to use them because don't want to copy the content of one file, is not something that I'm going to do.

PS. This theme will never replace LESS version of Balnk theme in the M2 core, it will always be a 3rd party theme, which is just a clone translated to SASS.

PSS. Please read ["Bug reports and contribution rules"](https://github.com/SnowdogApps/magento2-theme-blank-sass/blob/master/README.md#bug-reports-and-contribution-rules) before submitting feature requests.
