### ISSUE TITLE
categorie and checkout pages have excessive layout width

### ISSUE THREAD

**Issue by basbold** [SnowdogApps/magento2-theme-blank-sass#223]
## Issue description

Category and checkout pages have excessive layout width.

### Examples
`.page-layout-2columns-left .sidebar-main` on the categorie page has a width of 300% and `.opc-wrapper` has a calculated width of 1500%.

## Possible fix
I traced back a possible cause which was done in release 1.3.0. 

> reorganize imports of magento ui sass related files to match less theme structure (#204)

Extended `vendor/magento-ui/_lib.scss` and moved `variables` to the top of the import list.

```
//
//  Global lib
//  _____________________________________________

@import 'variables';
@import 'actions-toolbar';
...
```

**Comment by masi** [comment]
Had the same issue with .opc-wrapper (for Desktop).

Moving the import back to the top as basbold did fixed my problem as well.

**Comment by richardWebdezign** [comment]
Yeah, affected me too. `variables` needs to come before the other imports so that they can read the variables.

**Comment by karlhass15** [comment]
Saw the issue when we pushed to staging, but not on my local. I just used a body class to override them rather than find needed specificity, because I wouldn't know till it hit staging.

**Comment by PatrickWhitehouse** [comment]
I also had this issue, spent hours trying to resolve it. Luckily stumbled across this and you're right, moving variables to the top fixes it.

**Comment by stu177** [comment]
Any ETA for when this is pushed up in a release? Same question for #224.

**Comment by jeroenalewijns** [comment]
It ran into this problem many times

`vendor/snowdog/theme-blank-sass/styles/vendor/magento-ui/variables/_layout.scss` ln18 
$total-columns: 12 !default;

This var is used in the same file on ln 22 for `$layout-column__width: $total-columns !default;` and on ln 29 for $`layout-column-main__width-2-left: $layout-column__width - $layout-column__left-width !default;`.
But.... when you check the $total-columns var `@debug $total-columns` it is 1 and that's because of the file vendor/snowdog/theme-blank-sass/styles/vendor/magento-ui/_grids.scss on ln7.

Is there any ETA for this beautiful solution as told above?
