### ISSUE TITLE
clean install doesn't build if using dart-sass

### ISSUE THREAD

**Issue by pjschmidt3** [SnowdogApps/magento2-theme-blank-sass#243]
I'm using dart-sass instead of the default (in frontools) node-sass to compile styles, and with a brand new install of the theme, I get this:

```
[19:11:15] gulp-notify: [Error running Gulp] Error: ../../../var/view_preprocessed/frontools/pub/static/frontend/BBMC/bbmc-sass/styles/vendor/magento-ui/_pages.scss
Error: Duplicate argument.
   ╷
74 │     $_pager-action-text-decoration              : $pager-action__text-decoration,
```

It appears that the $_pager-action-text-decoration argument is indeed duplicated in _pages.scss:

```
 //  Page action item (previous-next)
    $_pager-action-text-decoration              : $pager-action__text-decoration,
    $_pager-action-text-decoration-hover        : $pager-action__hover__text-decoration,

    //  Page action item (previous-next) - default
    $_pager-action-color                        : $pager-action__color,
    $_pager-action-border                       : $pager-action__border,
    $_pager-action-background                   : $pager-action__background,
    $_pager-action-gradient-color-start         : $pager__gradient-color-start,
    $_pager-action-gradient-color-end           : $pager__gradient-color-end,
    // this is a duplicate
    $_pager-action-text-decoration              : $pager-action__text-decoration,
```

Everything works with node-sass, but it should be fixed in favor of valid scss anyway.

**Comment by Igloczek** [comment]
Thanks for the report. Such syntax issues probably should be addressed directly in the Magento core as [bug reports and contribution rules](https://github.com/SnowdogApps/magento2-theme-blank-sass#bug-reports-and-contribution-rules) says.

Also, this project is in an "only critical maintenance" mode, because we are not using it anymore, so unless the Dart will work out of the box, which seems to not be a case, or someone from the community provide such compatibility via PR and this will still be easy to maintain in the future (which means the Magento core code needs to have the same improvements), we are not planning to invest the time into it.

**Comment by Igloczek** [comment]
[We are closing this project.](https://github.com/SnowdogApps/magento2-theme-blank-sass/commit/77253d24ab00c05b2b91693fb25aeac4bebfa1de)
